### ISSUE TITLE
RdrCEF.exe drops .dll to disk and is blocked by FileBlockExecutable rule

### ISSUE THREAD

**Issue by mmb2-github** [NextronSystems/sysmon-config#43]
RdrCEF.exe dropping dll C:\Users\<username>\AppData\Local\Temp\acrocef_low\4616_1623006624\_platform_specific\win_x86\widevinecdm.dll 
to disk, something to do with viewing DRM material.  Being blocked by FileBlockExecutable.  Unsure if causing issues yet.

**Comment by nasbench** [comment]
That's interesting. Thanks for pointing this out.

I will add a comment to highlight this for future users who might want to comment that entry.
