### ISSUE TITLE
Line 239 Formatting of Registry Key

### ISSUE THREAD

**Issue by kevinelwell** [NextronSystems/sysmon-config#48]
On line 239 of the [sysmonconfig-trace.xml](https://github.com/Neo23x0/sysmon-config/blob/master/sysmonconfig-trace.xml)

`<TargetObject condition="is">\REGISTRY\MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Print\Printers\Microsoft Print to PDF\PrinterDriverData</TargetObject>`

The other Event ID 12,13,14 entries are formatted like `HKLM\SOFTWARE\Microsoft\SecurityManager\CapAuthz`

Was this intentional ?

**Comment by nasbench** [comment]
It's not intentional. It seems like a residue from an old config. Since the notation `\REGISTRY\...` was how sysmon used to show reg value before schema 3.30

I will fix this in a future PR.

Thanks for pointing it out.
