### ISSUE TITLE
Question about Archive function

### ISSUE THREAD

**Issue by ImanenigmaPro** [NextronSystems/sysmon-config#49]
Hi,
config sysmonconfig-trace.xml
on line 15    <ArchiveDirectory>Archive</ArchiveDirectory> (sets the name for the directory)
on lines 289-294  state disable archiving of the files

		<RuleGroup name="" groupRelation="or">
			
			<FileDelete onmatch="include">
				
			</FileDelete>
		</RuleGroup>
		
Is there a reason the archive directory is explicitly created  then files are effectively disabled from being written there?

Thank you.

**Comment by nasbench** [comment]
Hi,

I think during an update we forgot to comment out the archive directory. Since EID 23 can be very verbose. It was decided to use EID 26.
